import fs from "node:fs";
import path from "node:path";

const defaultToolRepo = "nugehs/repoctx";
const defaultToolRef = "main";
const workflowPath = ".github/workflows/repoctx-ci.yml";

export function initProject(targetPath = ".", options = {}) {
  const root = path.resolve(targetPath);
  if (!fs.existsSync(root)) {
    throw new Error(`target path does not exist: ${root}`);
  }

  const force = Boolean(options.force);
  const toolRepo = String(options.toolRepo ?? defaultToolRepo);
  const toolRef = String(options.toolRef ?? defaultToolRef);
  const operations = [];

  writeScaffoldFile(root, ".dev-context/README.md", contextReadme(toolRepo, toolRef), { force, operations });

  if (!options.noWorkflow) {
    writeScaffoldFile(root, workflowPath, workflowTemplate(toolRepo, toolRef), {
      force,
      operations,
    });
  }

  return {
    ok: true,
    root,
    force,
    toolRepo,
    toolRef,
    created: operations.filter((item) => item.action === "created").map((item) => item.path),
    updated: operations.filter((item) => item.action === "updated").map((item) => item.path),
    skipped: operations.filter((item) => item.action === "skipped").map((item) => item.path),
    nextSteps: [
      "Review the generated workflow before opening a PR.",
      "If the repoctx tool repository is private, add a DEV_CONTEXT_REPO_TOKEN secret and enable the token line in the workflow.",
      "Open or update a pull request to verify the PR comment and artifact.",
    ],
  };
}

export function formatInitSummary(result) {
  const lines = [`repoctx initialized: ${result.root}`, ""];
  lines.push(formatList("Created", result.created));
  lines.push(formatList("Updated", result.updated));
  lines.push(formatList("Skipped", result.skipped));
  lines.push("", "Next steps:");
  for (const step of result.nextSteps) {
    lines.push(`- ${step}`);
  }
  return lines.join("\n");
}

function writeScaffoldFile(root, relativePath, contents, { force, operations }) {
  const absolutePath = path.join(root, relativePath);
  const exists = fs.existsSync(absolutePath);
  if (exists && !force) {
    operations.push({ action: "skipped", path: relativePath });
    return;
  }

  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, contents);
  operations.push({ action: exists ? "updated" : "created", path: relativePath });
}

function formatList(title, values) {
  if (!values.length) {
    return `${title}: none`;
  }
  return [title, ...values.map((value) => `- ${value}`)].join("\n");
}

function contextReadme(toolRepo, toolRef) {
  return `# repoctx

This folder is managed by repoctx.

Generated assets:

- \`${workflowPath}\`: runs quality gates and PR review context generation on pull requests
- \`.dev-context/pr-review.md\`: generated by GitHub Actions and uploaded as an artifact

Tool source:

- Repository: ${toolRepo}
- Ref: ${toolRef}

Local command:

\`\`\`bash
repoctx pr . --base origin/main --out .dev-context/pr-review.md
\`\`\`
`;
}

function workflowTemplate(toolRepo, toolRef) {
  return `name: repoctx CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  review:
    name: Generate PR review context
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout pushed commit
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          ref: \${{ github.sha }}
          fetch-depth: 0

      - name: Checkout repoctx
        uses: actions/checkout@v4
        with:
          repository: ${toolRepo}
          ref: ${toolRef}
          path: .dev-context/tool
          # If ${toolRepo} is private, create a secret named DEV_CONTEXT_REPO_TOKEN
          # with read access and uncomment the next line.
          # token: \${{ secrets.DEV_CONTEXT_REPO_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install repoctx dependencies
        working-directory: .dev-context/tool
        run: npm ci

      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin "+\${{ github.base_ref }}:refs/remotes/origin/\${{ github.base_ref }}" --depth=1

      - name: Generate PR review context
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          node .dev-context/tool/src/cli.js pr . \\
            --base "origin/\${{ github.base_ref }}" \\
            --head HEAD \\
            --number "\${{ github.event.pull_request.number }}" \\
            --out .dev-context/pr-review.md \\
            --comment

      - name: Generate commit review context
        if: github.event_name == 'push'
        run: |
          BASE="\${{ github.event.before }}"
          if ! git rev-parse --verify "$BASE^{commit}" >/dev/null 2>&1; then
            if git rev-parse --verify "HEAD~1^{commit}" >/dev/null 2>&1; then
              BASE="HEAD~1"
            else
              BASE="HEAD"
            fi
          fi

          node .dev-context/tool/src/cli.js pr . \\
            --base "$BASE" \\
            --head "\${{ github.sha }}" \\
            --out .dev-context/pr-review.md

      - name: Upload PR review artifact
        uses: actions/upload-artifact@v4
        with:
          name: repoctx-pr-review
          path: .dev-context/pr-review.md
`;
}
