import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getAgentTools } from "../src/lib/agent-tools.js";

// The How It Works diagram is linked from the docs home page as *the* visual
// explanation of otito. It was hand-maintained and drifted for eighteen
// releases: it advertised a `repo_catalog` tool that no longer exists and never
// gained `agent_experience` or `convergence_score`. It is now generated from
// the same tool catalog the MCP server is derived from, and this test fails the
// moment the committed file stops matching that catalog.
//
// `npm run docs:diagram:check` additionally proves the whole file is
// byte-identical to a fresh render; this test isolates the property that
// actually misled readers, with a message that says how to fix it.

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const diagramPath = path.join(repoRoot, "docs", "assets", "otito-how-it-works.html");

/** Tool names carried by the diagram's node titles. */
function diagramToolNames(html) {
  return [...html.matchAll(/data-title="([a-z_]+)"/g)].map((match) => match[1]).sort();
}

test("the How It Works diagram covers exactly the shipped MCP tool catalog", () => {
  const html = fs.readFileSync(diagramPath, "utf8");
  const catalog = getAgentTools()
    .tools.map((tool) => tool.name)
    .sort();
  const onDiagram = diagramToolNames(html);

  const missing = catalog.filter((name) => !onDiagram.includes(name));
  const stale = onDiagram.filter((name) => !catalog.includes(name));

  assert.deepEqual(missing, [], `tools missing from the diagram — run \`npm run docs:diagram\``);
  assert.deepEqual(stale, [], `tools on the diagram that no longer exist — run \`npm run docs:diagram\``);
  assert.equal(onDiagram.length, catalog.length);
});

test("the diagram names every tool in its MCP surface description", () => {
  const html = fs.readFileSync(diagramPath, "utf8");
  const catalog = getAgentTools().tools.map((tool) => tool.name);

  const mcpNode = html.match(/data-id="mcp"[^>]*data-desc="([^"]*)"/);
  assert.ok(mcpNode, "the MCP entry node must carry a description");
  const description = mcpNode[1];

  assert.match(description, new RegExp(`exposing ${catalog.length} tools`), "the advertised tool count must match the catalog");
  for (const name of catalog) {
    assert.ok(description.includes(name), `${name} must be listed in the MCP surface description`);
  }
});

test("the diagram is marked generated so it is not hand-edited back into drift", () => {
  const html = fs.readFileSync(diagramPath, "utf8");
  assert.match(html, /Generated by scripts\/generate-how-it-works\.mjs/);
  assert.match(html, /npm run docs:diagram/);
});

test("every CLI-only stage on the page names a command the CLI still has", () => {
  const html = fs.readFileSync(diagramPath, "utf8");
  const help = execFileSync(process.execPath, [path.join(repoRoot, "src", "cli.js"), "help"], { encoding: "utf8" });
  const commands = [...html.matchAll(/data-kind="cli"[^>]*data-command="([a-z-]+)"/g)].map((match) => match[1]);

  assert.ok(commands.includes("attest"), "the page must show the post-merge attestation stage");
  assert.ok(commands.includes("calibrate") && commands.includes("regret"), "the page must show the history-graded stage");
  for (const command of new Set(commands)) {
    assert.match(help, new RegExp(`^\\s+otito ${command}\\b`, "m"), `otito ${command} is on the page but not in \`otito help\``);
  }
});
